### ISSUE TITLE
Legacy ReadyNas downloaded .Tivo files won't upload, creates error

### ISSUE THREAD

**Issue by grs123** [wmcbrine/pytivo#27]
The ReadyNas isn't working for pulling files to a Bolt from the ReadyNas.  The server doesn't show up on the Bolt.  It does show on my series 3.  So, I gave pytivo a shot.  It shows up on the Bolt, and seems to work, except I have found the following error happens on about 1 out of 5 saved shows, saved from the series 3. (Although I have also seen it on a show downloaded from the bolt, but I don't have as much experience with that yet.)

The files that won't upload to the bolt do upload fine using the ReadyNas interface on the Series 3.  They also won't upload to the Series 3 using the pyTivo interface.  The error is following:

ERROR:pyTivo:Exception during request from ('192.168.1.11', 53258)
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/Users/glenn/Downloads/pytivo-master/httpserver.py", line 91, in __init__
    client_address, server)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/Users/glenn/Downloads/pytivo-master/httpserver.py", line 131, in do_GET
    self.handle_file(query, splitpath)
  File "/Users/glenn/Downloads/pytivo-master/httpserver.py", line 248, in handle_file
    plugin.send_file(self, path, query)
  File "/Users/glenn/Downloads/pytivo-master/plugins/video/video.py", line 158, in send_file
    tsn, mime, thead)
  File "/Users/glenn/Downloads/pytivo-master/plugins/video/transcode.py", line 93, in transcode
    bufsize=(512 * 1024))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
AttributeError: 'NoneType' object has no attribute 'rfind'

**Comment by grs123** [comment]
This has been determined to be a problem with tivodecode, not pytivo.  Thus, the request would seem to be inappropriate here.

Withdrawn, unless of course someone knows the tivodecode people, or can suggest a path.
